Repository Hone12345678/lastMinute, pull requests merged in 2021-12, with the labels that each got.

#1 boilerplate html
  index.html
Labels: enhancement

#6 Develop
  assets/css/style.css
  index.html
  js/script.js
Labels: enhancement

#13 built user inputs and basic interactions with the API
  assets/js/script.js
  assets/js/seatGeakLogic.js
  seatGeek.html
Labels: enhancement

#17 improved display of events page and added save button
  assets/css/style.css
  assets/js/seatGeakLogic.js
  seatGeek.html
Labels: enhancement

#23 Feature/adding functioning modals to seat geek
  assets/css/seatgeek.css
  assets/js/seatGeakLogic.js
  seatGeek.html
Labels: enhancement

#26 added load for Events to Datenight
  assets/js/datenight.js
Labels: enhancement

#28 added additional styling to the event page to match overall theme
  assets/css/seatgeek.css
  assets/js/seatGeakLogic.js
  seatGeek.html
Labels: enhancement

#29 removed image placeholder from Dat Nite page
  dateNight.html
Labels: enhancement

#31 Update README.md
  README.md
Labels: enhancement

#36 Update README.md
  README.md
Labels: enhancement

#39 Update README.md
  README.md
Labels: documentation

#43 adding descriptive comments to seatGeek info and did some additional …
  assets/css/seatgeek.css
  assets/js/seatGeakLogic.js
  dateNight.html
  seatGeek.html
Labels: documentation, enhancement

#46 adding descriptive comments to css
  assets/css/seatgeek.css
Labels: documentation, enhancement

#47 Update README.md
  README.md
Labels: documentation, enhancement

#48 zip code bug fixes and formatting event type
  assets/js/seatGeakLogic.js
Labels: enhancement
